In [19]:
import librosa
import numpy as np
import os

In [20]:
inputFolder = "./ClassicalDataset"

files = os.listdir(inputFolder)

In [32]:
musicData = []

for file in files:
    path  = os.path.join(inputFolder, file)
    y, sr = librosa.load(path, mono=True)
    musicData.append(y)
    


In [33]:
musicData

[array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.        , 0.        , 0.        , ..., 0.00105836, 0.00103912,
        0.00112464], dtype=float32),
 array([-8.9302484e-06, -2.0383119e-05, -2.1295476e-05, ...,
         1.5302621e-06, -2.9437624e-06, -4.7035246e-07], dtype=float32),
 array([-0.00030378, -0.00059587, -0.00051626, ..., -0.00038461,
        -0.0003295 , -0.00035644], dtype=float32),
 array([-3.4894136e-05, -2.7486591e-05, -5.1781059e-05, ...,
        -2.6621790e-05, -7.7376935e-06,  7.6633660e-07], dtype=float32),
 array([-0.00027771, -0.00051348, -0.000496  , ...,  0.0004818 ,
         0.00048641,  0.00055622], dtype=float32),
 array([-2.1353619e-05, -1.3116455e-05, -2.0787440e-05, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00], dtype=float32),
 array([0.00037003, 0.00056732, 0.00048839, ..., 0.00155242, 0.0015579 ,
        0.00166632], dtype=float32),
 array([ 0.00102728,  0.00150568,  0.00169402, ..., -0.00404383,
        -0.00388197, -0.004

In [35]:
musicData = np.concatenate(musicData)

In [38]:
np.save("combinedMusicData", musicData)